// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

enum VIOLATION_TYPE {
    LATE,
    LEAVE,
    OTHER
}

enum CONDITION_TYPE {
    PERMISSION,
    NO_PERMISSION
}

enum PUNISH_TYPE {
    WARNING,
    FINE_OR_TICKET,
    SALARY_DEDUCATION_TYPE
}

enum SALARY_DEDUCATION_TYPE {
    MINUTE,
    HOUR,
    DAY,
    HALF_DAY,
    SHIFT_MINUTE,
    SHIFT_HOUR,
    SHIFT,
    HALF_SHIFT,
    TYPE
}

enum HANDLE_CASE_STATUS {
    UNSOLEVED,
    SOLVED
}

enum REQUEST_TYPE {
    LEAVE_PERMISSION,
    LATE_ARRIVAL,
    COME_BACK_SOON,
    OFFER_SALARY,
    SUBSIDIZE,
    RESIGN,
    RULE,
    IN_OUT_ON_BEHALF,
    SALARY_DEDUCATION
}

enum REASON_LEAVE_TYPE {
    SICK_LEAVE,
    MATERNITY_LEAVE,
    HAVE_PERSONAL_OR_FAMILY_MATTERS,
    ANNUAL_LEAVE,
    OTHER
}

enum REASON_LATE_TYPE {
    TRAFFIC_JAM,
    FEELING_TIRED_INSIDE,
    HAVE_PERSONAL_OR_FAMILY_MATTERS,
    OTHER
}

enum REASON_COME_BACK_SOON {
    MEDICAL_APPOINTMENT_SCHEDULE,
    THERE_IS_AN_EMERGENCY,
    HAVE_PERSONAL_OR_FAMILY_MATTERS,
    OTHER
}

enum REASON_COME_OFFER_SALARY {
    INCREASE_PRODUCTIVITY,
    INCREASE_LIVING_COSTS,
    INCREASED_RESPONSIBILITIES_AND_ROLES,
    OTHER
}

enum REASON_COME_SUBSIDIZE {
    LUNCH,
    PARKING_FEE,
    GASOLINE,
    OTHER
}

enum REASON_RESIGN {
    THE_ENVIRONMENT_IS_NOT_SUITABLE,
    UNSUITABLE_WORK,
    THE_WORK_IS_TOO_DIFFICULT,
    OTHER
}

enum NOTIFICATION_TYPE {
    REQUEST, // Related Request
    FINE_TICKET,
    WARNING, // Related Violation Company Rule
    REVIEW, // For HR & HR Manager: All request of employee
    HOLIDAY,
    TYPE,
    SALARY_DEDUCATION_TYPE
}

enum VIEW_ID_TYPE {
    VIEW_ALL,
    VIEW_ATTENDANCE,
    VIEW_SALARY
}

// Setting Time
enum FORM_OF_WORK {
    BY_DATE,
    WORK_IN_SHIFTS
}

enum OVERTIME {
    SALARY,
    MAKE_UP_FOR_TIME,
    NONE
}

enum SALARY_CLOSING_DATE {
    LAST_DATE_OF_EACH_MONTH
}

enum ATTENDANCE_TYPE {
    CHECK_IN,
    CHECK_OUT,
    OVER_TIME,
    CHECK_IN_ON_BEHALF,
    CHECK_OUT_ON_BEHALF
}
enum EMPLOYEE_MANAGEMENT_STATUS {
    NONE,
    PERMISSION,
    NO_PERMISSION,
    WAIT_REQUEST
}
enum ON_BEHALF_STATUS {
    INIT,
    HR_CONFIRM,
    HR_MANAGER_APPROVAL,
    HR_MANAGER_REJECT
}

enum REQUEST_STATUS {
    UN_READ,
    APPROVAL,
    REJECT
}

enum ROLE {
    ROOT,
    HR_MANAGER,
    HR,
    ACCOUNTANT,
    EMPLOYEE
}

enum ATTENDANCE_LIMIT_TYPE {
    FREE_ATTENDANCE,
    ONLY_ALLOW_AT_WORK
}

enum SHIFT_STATUS {
    LEAVE,
    LATE,
    ON_SCHEDULE
}

enum PERMISSION_STATUS {
    NO_PERMISSION,
    PERMISSION,
    NONE
}

enum EMPLOYEE_TURNOVER_TYPE {
    ON_BOARD,
    RESIGN
}
